spring.application.name=book-management
spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=postgres
spring.datasource.password=my!1rstPr0j3ct

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true